OUTREACH_TEMPLATES = {
    "helpful_observation": {
        "instagram": "Hey! Came across your page — really like [specific product/service]. Quick thing I noticed: your bio doesn't link to a website, so people probably have a harder time finding your menu/hours outside Instagram. I build sites for small businesses like yours — want me to put together a quick idea of what one could look like?",
        "facebook": "Hi [Name], love what you're doing at [Business] — [specific detail]. Noticed you don't have a website linked anywhere, which means a lot of potential customers searching on Google probably can't find you. I design websites for local businesses. Would you be open to seeing a quick mockup of what yours could look like?",
        "whatsapp": "Hi, this is [Your Name] — I came across [Business] on Instagram and really liked [specific detail]. Noticed you don't have a dedicated website yet, which could be limiting how many people find you outside social media. I build websites for small businesses — mind if I send over a quick idea?",
        "email": "Hi [Name],\n\nI was looking into [Business] and really liked [specific detail]. I noticed that you don't currently have a website listed. A lot of businesses in [location/niche] are losing out on potential customers simply because they are hard to find on Google.\n\nI specialize in building clean, fast websites for local businesses. Would you be open to me sending over a quick mockup of what a site could look like for you?\n\nBest,\n[Your Name]"
    },
    "business_growth": {
        "instagram": "Hey! Been seeing [Business] show up around [location/niche] — great engagement on your posts. One thing that could help you convert more of that into actual bookings/sales is a simple website people can land on and trust. I build fast, mobile-friendly sites for businesses like yours. Want to see a quick concept?",
        "facebook": "Hi [Name], your page for [Business] has solid traction — [specific detail]. A lot of businesses at that stage see a real jump once they have a proper website, since it makes it easier for people to convert from \"interested\" to \"customer.\" Want me to sketch out a quick idea for you?",
        "whatsapp": "Hi, I'm [Your Name]. I've noticed [Business] doing well on Instagram — [specific detail]. Businesses usually see more conversions once they pair that with a proper website, since it gives people a place to actually commit (book, order, inquire). Would you be open to seeing a quick idea of what that could look like?",
        "email": "Hi [Name],\n\nYour recent growth and traction for [Business] caught my eye, especially [specific detail]. At this stage, many businesses see a significant increase in conversions when they pair their social presence with a professional website where customers can easily book or buy.\n\nI build fast, mobile-friendly sites that help businesses convert visitors into customers. Would you be interested in a quick sketch of what this could look like for [Business]?\n\nBest,\n[Your Name]"
    },
    "website_improvement": {
        "instagram": "Hey! Checked out [Business]'s website — solid start. Noticed it's a bit slow to load on mobile though, which is where most of your visitors probably are. I build fast, modern sites (React/Next.js) that load quickly and look sharp on phones. Want me to put together a quick before/after idea?",
        "facebook": "Hi [Name], I visited [Business]'s website and it's clear you've put effort in. One thing I noticed — it's not fully optimized for mobile, and that can quietly cost you customers who bounce before they even see your services. I specialize in fast, mobile-first redesigns. Interested in seeing a quick mockup of an improved version?",
        "whatsapp": "Hi, I'm [Your Name]. I came across [Business]'s website — good foundation, but it looked a bit dated/slow on mobile when I checked. I build modern, fast websites and could put together a quick redesign concept so you can see the difference. Want me to send it over?",
        "email": "Hi [Name],\n\nI was visiting [Business]'s website today. You have a great foundation, but I noticed some loading and layout issues when viewing it on a mobile device. Since most of your traffic likely comes from phones, this could be causing potential customers to bounce.\n\nI specialize in fast, modern, mobile-first website redesigns. Would you be open to me putting together a quick before-and-after concept to show how we could improve the mobile experience?\n\nBest,\n[Your Name]"
    },
    "problem_solver": {
        "instagram": "Hey! Was checking out businesses in [location/niche] and tried loading your website on my phone — took a while and some things looked a bit off on mobile. That's a common (and fixable) issue. I build fast, mobile-friendly sites for businesses like yours. Want me to show you a quick fix idea?",
        "facebook": "Hi [Name], I tried visiting [Business]'s website on my phone and noticed it's not rendering great on mobile — probably losing you visitors who give up before finding what they need. I fix exactly this kind of thing for small businesses. Want me to send over a quick idea of what an improved version could look like?",
        "whatsapp": "Hi, this is [Your Name]. I checked out [Business]'s site on mobile and noticed some loading/layout issues — likely turning away visitors before they even see what you offer. This is something I fix regularly for small businesses. Mind if I send a quick concept showing how it could look instead?",
        "email": "Hi [Name],\n\nI recently tried visiting the [Business] website on my phone and noticed some layout and loading issues that make it difficult to navigate. This is a very common issue, but it often causes potential customers to leave before seeing what you offer.\n\nI regularly fix these kinds of issues for local businesses by building fast, mobile-friendly sites. Would you mind if I sent over a quick concept showing how these issues could be resolved?\n\nBest,\n[Your Name]"
    },
    "founder_to_business": {
        "instagram": "Hey! I'm a developer who builds websites for small businesses, and [Business] caught my eye — [specific detail]. I don't see a website linked, so I put a bit of thought into what one could look like for you. No pressure at all — want me to share the idea?",
        "facebook": "Hi [Name], I run a small web development practice building sites for businesses like yours, and [Business] stood out to me because of [specific detail]. I actually sketched a rough idea of what a website could look like for you — completely optional to check out, but want me to send it over?",
        "whatsapp": "Hi, I'm [Your Name], I build websites for small businesses. I came across [Business] and liked [specific detail] enough that I put together a rough concept of what a site could look like for you — no strings attached. Want me to send it so you can take a look?",
        "email": "Hi [Name],\n\nI'm [Your Name], and I run a small web development practice focused on helping businesses like yours. I came across [Business] recently and was really impressed by [specific detail].\n\nI noticed you don't have a website linked, so I went ahead and sketched a rough idea of what a site could look like for you. There are no strings attached at all, but I'd love to share it with you if you're open to it.\n\nBest,\n[Your Name]"
    }
}
