"""add state to business

Revision ID: 4b3e5f6g7h8i
Revises: 3a2c4d5b6e7f
Create Date: 2026-09-01 16:47:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b3e5f6g7h8i'
down_revision: Union[str, None] = '3a2c4d5b6e7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('businesses', sa.Column('state', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('businesses', 'state')
    # ### end Alembic commands ###
