"""Add social intelligence table

Revision ID: 5476916074b0
Revises: e0d66345c7a3
Create Date: 2026-08-23 09:31:23.473359
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '5476916074b0'
down_revision: str | None = 'e0d66345c7a3'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('social_intelligence',
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], name=op.f('fk_social_intelligence_business_id_businesses'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_social_intelligence'))
    )
    op.create_index(op.f('ix_social_intelligence_business_id'), 'social_intelligence', ['business_id'], unique=False)
    op.create_index('ix_social_intelligence_business_id_created', 'social_intelligence', ['business_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_social_intelligence_business_id_created', table_name='social_intelligence')
    op.drop_index(op.f('ix_social_intelligence_business_id'), table_name='social_intelligence')
    op.drop_table('social_intelligence')
    # ### end Alembic commands ###