"""add location fields to discovery_sessions

Revision ID: 5c4f6g7h8i9j
Revises: 4b3e5f6g7h8i
Create Date: 2026-09-01 17:05:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c4f6g7h8i9j'
down_revision: Union[str, None] = '4b3e5f6g7h8i'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('discovery_sessions', sa.Column('country', sa.String(length=255), nullable=True))
    op.add_column('discovery_sessions', sa.Column('state', sa.String(length=255), nullable=True))
    op.add_column('discovery_sessions', sa.Column('city', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('discovery_sessions', 'city')
    op.drop_column('discovery_sessions', 'state')
    op.drop_column('discovery_sessions', 'country')
    # ### end Alembic commands ###
