"""Add user_id to businesses and leads

Revision ID: e0d66345c7a3
Revises: 002
Create Date: 2026-08-11 19:15:38.737899
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'e0d66345c7a3'
down_revision: str | None = '002'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_business_contacts_slug'), 'business_contacts', ['slug'])
    op.alter_column('business_intelligence', 'data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False)
    # 1. Add user_id column as nullable initially
    op.add_column('businesses', sa.Column('user_id', sa.UUID(), nullable=True))
    op.create_index('ix_businesses_user_id', 'businesses', ['user_id'], unique=False)
    op.create_foreign_key(op.f('fk_businesses_user_id_users'), 'businesses', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    
    op.add_column('leads', sa.Column('user_id', sa.UUID(), nullable=True))
    op.create_index('ix_leads_user_id', 'leads', ['user_id'], unique=False)
    op.create_foreign_key(op.f('fk_leads_user_id_users'), 'leads', 'users', ['user_id'], ['id'], ondelete='CASCADE')

    # 2. Handle existing data
    conn = op.get_bind()
    user_id_result = conn.execute(sa.text("SELECT id FROM users ORDER BY created_at ASC LIMIT 1")).scalar()
    if user_id_result:
        # Assign leads to the user they were assigned_to, or the first user
        conn.execute(sa.text(f"UPDATE leads SET user_id = COALESCE(assigned_to, '{user_id_result}') WHERE user_id IS NULL"))
        # Assign businesses based on leads, or the first user
        conn.execute(sa.text(f"UPDATE businesses SET user_id = (SELECT l.user_id FROM leads l WHERE l.business_id = businesses.id LIMIT 1)"))
        conn.execute(sa.text(f"UPDATE businesses SET user_id = '{user_id_result}' WHERE user_id IS NULL"))
    else:
        # If there are no users, we delete existing businesses and leads since they are invalid anyway without a user.
        conn.execute(sa.text("DELETE FROM leads"))
        conn.execute(sa.text("DELETE FROM businesses"))

    # 3. Alter columns to NOT NULL
    op.alter_column('businesses', 'user_id', nullable=False)
    op.alter_column('leads', 'user_id', nullable=False)
    op.alter_column('opportunity', 'data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False)
    op.alter_column('proposal', 'content',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False)
    op.alter_column('search_history', 'filters',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.create_unique_constraint('uq_users_email', 'users', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_users_email', 'users', type_='unique')
    op.alter_column('search_history', 'filters',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('proposal', 'content',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('opportunity', 'data',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.drop_constraint(op.f('fk_leads_user_id_users'), 'leads', type_='foreignkey')
    op.drop_index('ix_leads_user_id', table_name='leads')
    op.drop_column('leads', 'user_id')
    op.drop_constraint(op.f('fk_businesses_user_id_users'), 'businesses', type_='foreignkey')
    op.drop_index('ix_businesses_user_id', table_name='businesses')
    op.drop_column('businesses', 'user_id')
    op.alter_column('business_intelligence', 'data',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.drop_constraint(op.f('uq_business_contacts_slug'), 'business_contacts', type_='unique')
    # ### end Alembic commands ###